### ISSUE TITLE
Figure out why local tests are failing after recent updates.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-super_scaffolding#75]
https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-super_scaffolding/199/workflows/ba1ab675-8a1b-4b5d-a341-f8bbcb2a2a5d/jobs/851

**Comment by andrewculver** [comment]
Same thing is happening on the base repo: https://app.circleci.com/pipelines/github/bullet-train-co/bullet_train-base/436/workflows/d4dff9e0-1c3a-440a-88a4-8e4c3a896706/jobs/1774

**Comment by gazayas** [comment]
Linking https://github.com/bullet-train-co/bullet_train-api/pull/21 here, will look into it more here today.

**Comment by gazayas** [comment]
Still wrestling with this one and opened a ticket with CircleCI.
They pointed me to these docs, which I had seen previously and unfortunately doesn't have too much information unless I'm just not reading into it enough: https://circleci.com/docs/variables#built-in-environment-variables.

I'll write again soon if I make any progress.

**Comment by gazayas** [comment]
The reason our tests are failing is due to eager loading, and our individual packages are trying to load classes/modules from within the context of other packages that aren't being included.

## Why these tests pass locally
1. At the starter repo level: All of the necessary packages are available, so we don't get any errors.
2. At the package level: Unit tests at the package level don't load/run every class/module, so we don't get any errors.

## What we need to change in these packages
Here are the two main problems:
1. `include strong_parameters_from_api` is trying to get `StrongParameters` from `BulletTrain::Api` when `BulletTrain::Api` isn't present (exists in `bullet_train-api`).
3. Classes are trying to inherit from `Api::V1::ApplicationController` when it isn't present (`exists in the starter repository`).

I've provided a solution with the two PRs above this comment, but if they aren't what we need, at least we know what's causing the issue and what we need to address.
